spring:
  application:
    name: SnapTweet
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SnapTweet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  data:
    mongodb:
      host: localhost
      port: 27017
      database: SnapTweet
      authentication-database: ADMIN

server:
  port: 8080
